-- Removed DROP TABLE statements for production safety

-- Create Users Table (Now using UUID to match Supabase Auth)
CREATE TABLE users (
  id UUID PRIMARY KEY, -- Matches auth.users.id
  email TEXT UNIQUE NOT NULL,
  password TEXT, -- Keeping for legacy/fallback, but Supabase Auth handles passwords
  name TEXT,
  google_id TEXT UNIQUE,
  role TEXT DEFAULT 'user',
  token_version INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create Password Resets Table
CREATE TABLE password_resets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES users(id) ON DELETE CASCADE,
  token_hash TEXT NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  used BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create Profiles Table
CREATE TABLE profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES users(id) ON DELETE CASCADE UNIQUE,
  bio TEXT,
  avatar_url TEXT,
  theme_preference TEXT DEFAULT 'dark',
  notifications_enabled BOOLEAN DEFAULT TRUE,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create Clubs Table
CREATE TABLE clubs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  description TEXT NOT NULL,
  location TEXT,
  contact_info TEXT,
  image_url TEXT,
  established_year TEXT,
  google_maps_url TEXT,
  latitude DECIMAL(10, 7),
  longitude DECIMAL(10, 7),
  is_verified BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  user_id UUID REFERENCES users(id) ON DELETE SET NULL
);

-- Create Events Table
CREATE TABLE events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  club_id BIGINT REFERENCES clubs(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  date TIMESTAMPTZ NOT NULL,
  location TEXT,
  image_url TEXT,
  category TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  user_id UUID REFERENCES users(id) ON DELETE SET NULL
);

-- Create Tickets Table
CREATE TABLE tickets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT REFERENCES events(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  price_inr DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
  capacity INTEGER NOT NULL DEFAULT 100,
  sold INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create Orders Table
CREATE TABLE orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES users(id) ON DELETE SET NULL,
  ticket_id BIGINT REFERENCES tickets(id) ON DELETE CASCADE,
  quantity INTEGER NOT NULL DEFAULT 1,
  total_amount_inr DECIMAL(10, 2) NOT NULL,
  platform_fee_inr DECIMAL(10, 2) NOT NULL,
  payment_id TEXT UNIQUE,
  razorpay_payment_id TEXT UNIQUE,
  status TEXT NOT NULL DEFAULT 'PENDING',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create Event Registrations Table
CREATE TABLE event_registrations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
  event_id BIGINT REFERENCES events(id) ON DELETE CASCADE,
  user_id UUID REFERENCES users(id) ON DELETE SET NULL,
  attendee_name TEXT NOT NULL,
  phone TEXT NOT NULL,
  college_id TEXT,
  dietary_preference TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  checked_in BOOLEAN DEFAULT FALSE
);

-- Performance Indexes
CREATE INDEX IF NOT EXISTS idx_clubs_category ON clubs(category);
CREATE INDEX IF NOT EXISTS idx_events_club_id ON events(club_id);
CREATE INDEX IF NOT EXISTS idx_tickets_event_id ON tickets(event_id);

-- ==========================================
-- SUPABASE AUTH INTEGRATION TRIGGERS
-- ==========================================

-- Function to automatically copy new Supabase Auth users into our public.users table
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.users (id, email, name, role)
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'name', split_part(NEW.email, '@', 1)),
    CASE WHEN lower(NEW.email) = lower(current_setting('app.admin_email', true)) THEN 'admin' ELSE 'user' END
  );
  
  -- Automatically create an empty profile for them
  INSERT INTO public.profiles (user_id, bio, avatar_url, theme_preference, notifications_enabled)
  VALUES (
    NEW.id,
    '',
    COALESCE(NEW.raw_user_meta_data->>'avatar_url', ''),
    'dark',
    true
  );
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger to call the function every time a user signs up via Google/GitHub/Email
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- ==========================================
-- TICKET SALES RPC FUNCTION
-- ==========================================

-- Atomically increment ticket sales to prevent TOCTOU race conditions
CREATE OR REPLACE FUNCTION increment_ticket_sold(p_ticket_id BIGINT)
RETURNS SETOF tickets
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  UPDATE tickets
  SET sold = sold + 1
  WHERE id = p_ticket_id AND sold < capacity
  RETURNING *;
END;
$$;

-- ==========================================
-- REVIEWS SYSTEM
-- ==========================================

-- Create Reviews Table
CREATE TABLE reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  club_id BIGINT REFERENCES clubs(id) ON DELETE CASCADE,
  user_id UUID REFERENCES users(id) ON DELETE CASCADE,
  rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
  comment TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(club_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_reviews_club_id ON reviews(club_id);

-- ==========================================
-- FOLLOWERS SYSTEM
-- ==========================================

-- Create Club Followers Table
CREATE TABLE club_followers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  club_id BIGINT REFERENCES clubs(id) ON DELETE CASCADE,
  user_id UUID REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(club_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_club_followers_club_id ON club_followers(club_id);
CREATE INDEX IF NOT EXISTS idx_club_followers_user_id ON club_followers(user_id);

-- ==========================================
-- CLUB TEAM MANAGEMENT
-- ==========================================

-- Create Club Members Table
CREATE TABLE club_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  club_id BIGINT REFERENCES clubs(id) ON DELETE CASCADE,
  user_id UUID REFERENCES users(id) ON DELETE CASCADE,
  role TEXT NOT NULL CHECK (role IN ('editor', 'moderator')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(club_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_club_members_club_id ON club_members(club_id);

-- ==========================================
-- EVENT DISCUSSION / COMMENT THREADS
-- ==========================================

CREATE TABLE event_comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT REFERENCES events(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  content TEXT NOT NULL CHECK (char_length(content) > 0 AND char_length(content) <= 1000),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_event_comments_event_id ON event_comments(event_id);
CREATE INDEX IF NOT EXISTS idx_event_comments_user_id ON event_comments(user_id);

-- ==========================================
-- CLUB OWNER ANALYTICS
-- ==========================================

CREATE TABLE club_analytics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  club_id BIGINT REFERENCES clubs(id) ON DELETE CASCADE NOT NULL,
  view_date DATE NOT NULL DEFAULT CURRENT_DATE,
  page_views INTEGER DEFAULT 0,
  UNIQUE(club_id, view_date)
);

CREATE INDEX IF NOT EXISTS idx_club_analytics_club_id ON club_analytics(club_id);
CREATE INDEX IF NOT EXISTS idx_club_analytics_date ON club_analytics(view_date);
